// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoRoboNddTech.Data;

namespace ProjetoRoboNddTech.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210331035235_CriacaoInicialTabela")]
    partial class CriacaoInicialTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ProjetoRoboNddTech.Models.BracoMovimento", b =>
                {
                    b.Property<int>("BracoMovimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BracoMovimentoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BracoMovimentoId");

                    b.ToTable("BracoMovimento");
                });

            modelBuilder.Entity("ProjetoRoboNddTech.Models.CabecaInclinacaoMovimento", b =>
                {
                    b.Property<int>("CabecaInclinacaoMovimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CabecaInclinacaoMovimentoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CabecaInclinacaoMovimentoId");

                    b.ToTable("CabecaInclinacaoMovimento");
                });

            modelBuilder.Entity("ProjetoRoboNddTech.Models.CabecaRotacaoMovimento", b =>
                {
                    b.Property<int>("CabecaRotacaoMovimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CabecaRotacaoMovimentoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CabecaRotacaoMovimentoId");

                    b.ToTable("CabecaRotacaoMovimento");
                });

            modelBuilder.Entity("ProjetoRoboNddTech.Models.Robo", b =>
                {
                    b.Property<int>("RoboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("movimentoBracoDireitoAtualId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoBracoDireitoUltimoId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoBracoEsquerdoAtualId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoBracoEsquerdoUltimoId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoCabecaInclinacaoAtualId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoCabecaInclinacaoUltimoId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoCabecaRotacaoAtualId")
                        .HasColumnType("int");

                    b.Property<int?>("movimentoCabecaRotacaoUltimoId")
                        .HasColumnType("int");

                    b.HasKey("RoboId");

                    b.HasIndex("movimentoBracoDireitoAtualId");

                    b.HasIndex("movimentoBracoDireitoUltimoId");

                    b.HasIndex("movimentoBracoEsquerdoAtualId");

                    b.HasIndex("movimentoBracoEsquerdoUltimoId");

                    b.HasIndex("movimentoCabecaInclinacaoAtualId");

                    b.HasIndex("movimentoCabecaInclinacaoUltimoId");

                    b.HasIndex("movimentoCabecaRotacaoAtualId");

                    b.HasIndex("movimentoCabecaRotacaoUltimoId");

                    b.ToTable("Robo");
                });

            modelBuilder.Entity("ProjetoRoboNddTech.Models.Robo", b =>
                {
                    b.HasOne("ProjetoRoboNddTech.Models.BracoMovimento", "MovimentoBracoDireitoAtual")
                        .WithMany()
                        .HasForeignKey("movimentoBracoDireitoAtualId");

                    b.HasOne("ProjetoRoboNddTech.Models.BracoMovimento", "MovimentoBracoDireitoUltimo")
                        .WithMany()
                        .HasForeignKey("movimentoBracoDireitoUltimoId");

                    b.HasOne("ProjetoRoboNddTech.Models.BracoMovimento", "MovimentoBracoEsquerdoAtual")
                        .WithMany()
                        .HasForeignKey("movimentoBracoEsquerdoAtualId");

                    b.HasOne("ProjetoRoboNddTech.Models.BracoMovimento", "MovimentoBracoEsquerdoUltimo")
                        .WithMany()
                        .HasForeignKey("movimentoBracoEsquerdoUltimoId");

                    b.HasOne("ProjetoRoboNddTech.Models.CabecaRotacaoMovimento", "MovimentoCabecaInclinacaoAtual")
                        .WithMany()
                        .HasForeignKey("movimentoCabecaInclinacaoAtualId");

                    b.HasOne("ProjetoRoboNddTech.Models.CabecaRotacaoMovimento", "MovimentoCabecaInclinacaoUltimo")
                        .WithMany()
                        .HasForeignKey("movimentoCabecaInclinacaoUltimoId");

                    b.HasOne("ProjetoRoboNddTech.Models.CabecaRotacaoMovimento", "MovimentoCabecaRotacaoAtual")
                        .WithMany()
                        .HasForeignKey("movimentoCabecaRotacaoAtualId");

                    b.HasOne("ProjetoRoboNddTech.Models.CabecaRotacaoMovimento", "MovimentoCabecaRotacaoUltimo")
                        .WithMany()
                        .HasForeignKey("movimentoCabecaRotacaoUltimoId");

                    b.Navigation("MovimentoBracoDireitoAtual");

                    b.Navigation("MovimentoBracoDireitoUltimo");

                    b.Navigation("MovimentoBracoEsquerdoAtual");

                    b.Navigation("MovimentoBracoEsquerdoUltimo");

                    b.Navigation("MovimentoCabecaInclinacaoAtual");

                    b.Navigation("MovimentoCabecaInclinacaoUltimo");

                    b.Navigation("MovimentoCabecaRotacaoAtual");

                    b.Navigation("MovimentoCabecaRotacaoUltimo");
                });
#pragma warning restore 612, 618
        }
    }
}
